from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "MANIFEST.json"
START_HERE_PATH = ROOT / "START_HERE.md"


PATCH_NOTES = {
    "ATLAS-GOV-001": "added this resume entrypoint.",
    "ATLAS-GOV-002": "added governance enforcement and validation.",
    "ATLAS-GOV-003": "added backup and rollback protocol.",
    "ATLAS-GOV-004": "added generated entrypoint protocol.",
    "ATLAS-GOV-005": "added canonical pipeline alignment.",
    "ATLAS-GOV-006": "reclassified governance patches out of the PAC-007.2 namespace.",
    "ATLAS-GOV-007": "removed reclassified legacy PAC folders from the active Current surface.",
    "ATLAS-GOV-008": "defined DONE as the final status for completed PACs.",
    "ATLAS-GOV-009": "requires assistants to say whether memory-relevant information was recorded in Atlas.",
    "ATLAS-GOV-010": "separated local backups from lightweight assistant handoff packages.",
}


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def status_label(status: str) -> str:
    return status.replace("_", " ").lower()


def pac_sort_key(pac_id: str) -> tuple[int, list[int | str], str]:
    if pac_id.startswith("PAC-"):
        value = pac_id[len("PAC-") :]
        group = 0
        separators = "."
    elif pac_id.startswith("ATLAS-GOV-"):
        value = pac_id[len("ATLAS-GOV-") :]
        group = 1
        separators = ".-"
    else:
        value = pac_id
        group = 2
        separators = ".-"

    normalized = value
    for separator in separators:
        normalized = normalized.replace(separator, ".")
    parts: list[int | str] = []
    for part in normalized.split("."):
        parts.append(int(part) if part.isdigit() else part)
    return group, parts, pac_id


def next_task(manifest: dict) -> str:
    explicit = manifest.get("next_task")
    if isinstance(explicit, str) and explicit.strip():
        return explicit.strip()
    return "PAC-007.3 - Memory Commit"


def next_task_context(task: str) -> list[str]:
    if task.startswith("PAC-008"):
        return [
            "PAC-008 should consume committed memory and generate cognitive views and handover artifacts:",
            "",
            "- user memory view",
            "- project memory view",
            "- shared memory view",
            "- current handover context",
        ]

    if task.startswith("No active PAC"):
        return [
            "The canonical continuity pipeline through PAC-009 is done.",
            "",
            "The next structural step should define the next Atlas roadmap item before implementation.",
        ]

    return [
        "PAC-007.3 should read PAC-007.2 selection artifacts and commit only selected candidates into the appropriate future memory domain:",
        "",
        "- `user/memory.json`",
        "- `projects/<project_id>/memory.json`",
        "- `shared/memory.json`",
    ]


def practical_next_step(task: str) -> str:
    if task.startswith("PAC-008"):
        return "Define `Current/PAC-008/STATUS.md` and the cognitive view / handover generation contract before implementation."
    if task.startswith("No active PAC"):
        return "Review PAC-008 outputs and define the next Atlas roadmap item under the appropriate PAC or ATLAS-GOV namespace."
    return "Create `Current/PAC-007.3/STATUS.md` and define the memory commit contract before implementation."


def render_start_here(manifest: dict) -> str:
    read_order = manifest.get("recommended_read_order", [])
    statuses = manifest.get("status", {})
    backup_policy = manifest.get("backup_policy", {})
    canonical_pipeline = manifest.get("canonical_pipeline", [])
    task = next_task(manifest)

    lines: list[str] = [
        "# Welcome to Atlas",
        "",
        "This is the human entry point for resuming the Atlas project.",
        "",
        "This file is generated by `tools/atlas_generate_start_here.py`.",
        "",
        "Do not edit this file manually. Update `MANIFEST.json`, status files, or the generator, then run:",
        "",
        "```bash",
        "py tools/atlas_generate_start_here.py",
        "```",
        "",
        "If you are a new assistant, read these files in this order:",
        "",
    ]

    for index, item in enumerate(read_order[1:] if read_order and read_order[0] == "START_HERE.md" else read_order, 1):
        lines.append(f"{index}. `{item}`")

    lines.extend(
        [
            "",
            "Before editing anything structural, run:",
            "",
            "```bash",
            "py tools/atlas_validate.py",
            "```",
            "",
            "Then follow `GOVERNANCE/CHANGE_PROTOCOL.md`.",
            "",
            "Before future structural changes, create a rollback snapshot:",
            "",
            "```bash",
            "py tools/atlas_backup.py <PAC_ID>",
            "```",
            "",
            "## Resume Here",
            "",
            "Atlas is a cognitive continuity subsystem.",
            "",
            "Current state:",
            "",
        ]
    )

    for pac_id in sorted(statuses, key=pac_sort_key):
        lines.append(f"- {pac_id} is {status_label(str(statuses[pac_id]))}.")
    for pac_id in sorted(PATCH_NOTES, key=pac_sort_key):
        if pac_id in statuses:
            lines.append(f"- {pac_id} {PATCH_NOTES[pac_id]}")
    lines.append("- PAC-007.2 does not commit memory.")

    lines.extend(
        [
            "",
            "The next task is:",
            "",
            "```text",
            task,
            "```",
            "",
            *next_task_context(task),
            "",
            "## Core Invariant",
            "",
            "An artifact never modifies its source artifact.",
            "",
            "Each stage reads the previous artifact and produces a new artifact.",
            "",
            "## Current Pipeline",
            "",
            "Canonical PAC order:",
            "",
            "```text",
        ]
    )

    if isinstance(canonical_pipeline, list):
        for item in canonical_pipeline:
            if not isinstance(item, dict):
                continue
            pac = item.get("pac")
            role = item.get("role")
            if isinstance(pac, str) and isinstance(role, str):
                lines.append(f"{pac:<9} {role}")

    lines.extend(
        [
            "```",
            "",
            "Artifact flow:",
            "",
            "```text",
            "Conversation",
            "    -> Session",
            "    -> Candidate knowledge",
            "    -> Validation artifact",
            "    -> Selection / classification artifact",
            "    -> Memory Commit",
            "    -> Cognitive views & handover",
            "```",
            "",
            "## Important Boundaries",
            "",
            "PAC-007.2:",
            "",
            "- selects candidate information;",
            "- classifies kept candidates as `user`, `project`, or `shared`;",
            "- writes `sessions/selection/<session_id>.selection.json`;",
            "- does not write memory files.",
            "",
            "PAC-007.3:",
            "",
            "- should commit selected candidates into memory;",
            "- should preserve provenance;",
            "- should ignore `keep=false` candidates;",
            "- should not modify source session, analysis, validation, or selection artifacts.",
            "",
            "PAC-008:",
            "",
            "- generates cognitive views and handovers from committed memory;",
            "- does not modify source memory files.",
            "",
            "PAC-009:",
            "",
            "- reviews, updates, deprecates, and merges committed memory entries;",
            "- preserves maintenance history;",
            "- does not physically delete memory entries.",
            "",
            "## Governance Commands",
            "",
            "```bash",
            "py tools/atlas_validate.py",
            "py tools/atlas_backup.py <PAC_ID>",
            "py tools/atlas_handoff.py",
            "py tools/atlas_generate_start_here.py",
            "```",
            "",
            "## Backup Policy",
            "",
            f"- Directory: `{backup_policy.get('directory', 'BACKUPS/')}`",
            f"- Tool: `{backup_policy.get('tool', 'tools/atlas_backup.py')}`",
            f"- Enforced from: `{backup_policy.get('enforced_from', 'ATLAS-GOV-003')}`",
            "",
            "## Practical Next Step",
            "",
            practical_next_step(task),
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="atlas_generate_start_here")
    parser.add_argument("--check", action="store_true", help="Fail if START_HERE.md is not up to date")
    args = parser.parse_args(argv)

    manifest = load_manifest()
    content = render_start_here(manifest)

    if args.check:
        current = START_HERE_PATH.read_text(encoding="utf-8") if START_HERE_PATH.exists() else ""
        if current != content:
            print("START_HERE.md is not up to date; run py tools/atlas_generate_start_here.py")
            return 1
        print("START_HERE.md is up to date")
        return 0

    START_HERE_PATH.write_text(content, encoding="utf-8")
    print("START_HERE.md generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
